global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "microservicio"
    static_configs:
      - targets: ["microservicio:8001"]
